import {
  MessageCircle,
  Users,
  UserCircle,
  Newspaper,
  Image,
  Sun,
  MoonStar,
  Monitor,
  Network,
  LogOut,
  Settings,
  AlertTriangle,
  ChevronDown,
  Menu,
  Loader2,
  UserMinus,
  MessageSquare,
  MoreHorizontal,
  ChevronLeft,
  ChevronRight,
  Check,
  Undo2,
  X,
  MoreVertical,
  SendHorizonal,
  Paperclip,
  Upload,
  Trash2,
  Pencil,
  Heart,
  UserPlus,
  UserCheck,
  Search,
  SearchSlash,
  Mailbox,
  UserSearch,
  UserX,
  ArrowUpRight,
  ArrowDownLeft,
  MonitorSmartphone
} from 'lucide-react';

export const Icons = {
  myProfile: UserCircle,
  news: Newspaper,
  photos: Image,
  messenger: MessageCircle,
  friends: Users,
  lightMode: Sun,
  darkMode: MoonStar,
  systemMode: Monitor,
  appLogo: Network,
  signOut: LogOut,
  settings: Settings,
  alertTriangle: AlertTriangle,
  arrowDown: ChevronDown,
  arrowLeft: ChevronLeft,
  arrowRight: ChevronRight,
  mobileMenu: Menu,
  spinner: Loader2,
  unfriend: UserMinus,
  writeMessage: MessageSquare,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  accept: Check,
  undo: Undo2,
  reject: X,
  sendMessage: SendHorizonal,
  attach: Paperclip,
  upload: Upload,
  trash: Trash2,
  edit: Pencil,
  heart: Heart,
  addUser: UserPlus,
  acceptUser: UserCheck,
  searchUser: UserSearch,
  rejectUser: UserX,
  search: Search,
  resetSearch: SearchSlash,
  requests: Mailbox,
  outgoingRequests: ArrowUpRight,
  incomingRequests: ArrowDownLeft,
  online: MonitorSmartphone
};
